### PR TITLE
validate whether array has only unique items

### PR DESCRIPTION
**Pull request by t3h2mas**
Adds the `unique` validation option for arrays.

Tested and added to docs

### CODE REVIEW

**Comment by talyssonoc** [comment]
Hello, @t3h2mas, sorry for the delay on reviewing that, and thanks for the contribution :smile:

I have the intention to merge it, can you resolve the conflict?

**Comment by t3h2mas** [comment]
@talyssonoc should be resolved :+1:

**Comment by talyssonoc** [comment]
Thanks for the contribution, @t3h2mas! Gonna release soon :smile:

**Comment by talyssonoc** [comment]
@t3h2mas, just published 1.8.0 with your contribution!

**Pull request merged**
